[package]
name = "MainFrame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
syn = "2.0.87"

[dependencies.rocket_db_pools]
version = "0.2.0"
features = ["sqlx_sqlite"] # , "sqlx_mysql"
#features = ["sqlx_sqlite", "sqlx_mssql","sqlx_mysql"]

[dependencies]
rocket = { version = "0.5.1", features = ["secrets"] }
sqlx = {version = "0.7.0", features = ["sqlite"]}#, features = ["runtime-async-std", "sqlite", "mssql"]}
async-trait = "0.1.57"
data-encoding = "2.3.2"
rand = "0.8.5"
pbkdf2 = "0.12.2"
ring = "0.17.8"
rocket-multipart-form-data = "0.10.7"
base64 = "0.22.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.87"
rocket_dyn_templates = { version = "0.2.0", features = ["handlebars"] }
chrono = "0.4.23"
rocket-download-response = "0.5.4"
#paste = "1.0.9"